name: Build
on:
  workflow_call:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EARTHLY_TOKEN: ${{ secrets.EARTHLY_TOKEN }}
      EARTHLY_ORG: ${{ secrets.EARTHLY_ORG }}
      EARTHLY_SATELLITE: ${{ secrets.EARTHLY_SATELLITE }}
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: ^0.8.0
          use-cache: true
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Build
        run: |
          earthly --ci --allow-privileged --output +all
          ls -al
      - uses: actions/upload-artifact@v3
        with:
          path: |
            output/*
